home picture finish
WildCodeSchool/orleans-0919-php-gabare pull request #104
Opened 2019-12-12 17:20 UTC by LucasThvn

2019-12-12 18:34 UTC, ghost approved these changes

2019-12-12 19:11 UTC, ankwachu approved these changes

2019-12-12 21:20 UTC, sblondeau requested changes

2019-12-12 21:20 UTC, sblondeau commented on templates/_header.html.twig
> +    <div class="cooperators position-absolute p-2">900 Coopérateurs</div>
je mettrais cette ligne dans une future US, car il faut que le chiffre soit dynamiquement mis à jour, sinon la fonctionnalité n'est pas bonne...

2019-12-12 21:38 UTC, bcarme commented on templates/_header.html.twig
> +    <div class="cooperators position-absolute p-2">900 Coopérateurs</div>
elle fait partie d'une autre user story dans notre backlog on l'a mis en dur pour le rendu client. Suite au rdv de ce matin,  l'environnement dev de l'api ne marche pas, c'est toujours par terre, il n'a toujours pas contacté le support client...

2019-12-12 21:40 UTC, bcarme commented on templates/_header.html.twig
> +    <div class="cooperators position-absolute p-2">900 Coopérateurs</div>
Donc on n'est pas près de l'avoir...

2019-12-12 21:45 UTC, bcarme commented on templates/_header.html.twig
> +    <div class="cooperators position-absolute p-2">900 Coopérateurs</div>
Sinon on le fera dynamiquement depuis l'admin en créant un update dans une autre user story

2019-12-13 08:01 UTC, sblondeau requested changes

2019-12-13 08:01 UTC, sblondeau commented on templates/_header.html.twig
> +    <div class="cooperators position-absolute p-2">900 Coopérateurs</div>
enlève la ligne quand meme pour le principe ;-)

2019-12-13 09:01 UTC, bcarme approved these changes

2019-12-13 09:13 UTC, merged