nav active page nous-rejoindre
WildCodeSchool/orleans-0919-php-gabare pull request #208
Opened 2019-12-18 10:08 UTC by bcarme

2019-12-18 10:14 UTC, ankwachu approved these changes

2019-12-18 15:44 UTC, sblondeau requested changes

2019-12-18 15:44 UTC, sblondeau commented on templates/join_us/includes/_stripe.html.twig
> +            <h1 class="titlePhoto w-100 text-center">Venez no us rejoindre !</h1>
un espace en trop en "no" et "us"

2019-12-21 11:08 UTC, ankwachu approved these changes

2019-12-22 10:35 UTC, sblondeau approved these changes

2019-12-22 10:35 UTC, merged