page QSN afficher les pionniers
WildCodeSchool/orleans-0919-php-gabare pull request #211
Opened 2019-12-22 13:26 UTC by ankwachu

2019-12-22 16:11 UTC, bcarme approved these changes

2019-12-24 10:47 UTC, sblondeau requested changes

2019-12-24 10:47 UTC, sblondeau commented on src/Controller/AboutUsController.php
> +            ->findBy(array('activity' => '4'));
[] et non array()
et le activity '4' correspont à quoi ? on ne met surtout pas d'id de BDD "en dur" dans le code

2019-12-24 11:46 UTC, ankwachu commented on src/Controller/AboutUsController.php
> +            ->findBy(array('activity' => '4'));
activity 4 correspond à Pionnier(constante dans ActivityFixtures)
je veux récupérer tous les Workers associés à l'Activity Pionnier.

2019-12-24 13:05 UTC, ankwachu commented
Message d'erreur de Travis sur la méthode query builder que j'ai créée,
j'arrive à utiliser la méthode mais Travis me signale une erreur

2019-12-24 13:38 UTC, bcarme approved these changes

2019-12-27 16:13 UTC, sblondeau approved these changes

2019-12-27 16:13 UTC, merged