S03 us21 agenda
WildCodeSchool/orleans-0919-php-gabare pull request #219
Opened 2019-12-29 15:47 UTC by bcarme

2019-12-29 17:14 UTC, ankwachu approved these changes

2019-12-30 13:45 UTC, sblondeau requested changes

2019-12-30 13:45 UTC, sblondeau commented on src/Repository/TimetableRepository.php
> +            ->setMaxResults(12);
fais une constante au lieu de mettre "12" en dur

2019-12-30 13:45 UTC, sblondeau commented on src/Entity/Timetable.php
> +     * @ORM\Column(type="date")
ajoute des @assert

2020-01-01 18:06 UTC, sblondeau requested changes

2020-01-01 18:06 UTC, sblondeau commented on src/Entity/Timetable.php
> +     * @Assert\Date
si c'est une heure, tu as un @Assert\Time et non Date à mettre

2020-01-02 08:58 UTC, ankwachu approved these changes

2020-01-02 13:23 UTC, sblondeau approved these changes

2020-01-02 13:23 UTC, merged