S03US15D - afficher les membres du CA
WildCodeSchool/orleans-0919-php-gabare pull request #220
Opened 2019-12-30 22:44 UTC by ankwachu

2019-12-31 08:38 UTC, bcarme approved these changes

2020-01-01 18:08 UTC, sblondeau requested changes

2020-01-01 18:08 UTC, sblondeau commented on templates/about_us/includes/_CA-Member.html.twig
> +            {% for CAMember in CAMembers %}
si les 3 cartes sont identiques pour les 3 catégories de members, tu peux sans doute refacto le code de la card via un include que tu réutiliserais pour tous au lieu d'en faire 3 différents. On en rediscute demain

2020-01-01 18:11 UTC, ankwachu commented on templates/about_us/includes/_CA-Member.html.twig
> +            {% for CAMember in CAMembers %}
il y a l'email en plus sur les cartes membres CA sauf si le client change d'avis

2020-01-02 13:39 UTC, closed without merging