S03US49 - ajout CRUD Index Worker
WildCodeSchool/orleans-0919-php-gabare pull request #228
Opened 2020-01-02 20:53 UTC by ankwachu

2020-01-03 12:46 UTC, bcarme approved these changes

2020-01-06 08:53 UTC, sblondeau requested changes

2020-01-06 08:53 UTC, sblondeau commented on src/Controller/AdminWorkerController.php
> +            'workers' => $workerRepository->findAll(),
il faudrait les classer. Par ordre alphabétique, ou par activité/alphabétique

2020-01-06 14:50 UTC, ghost approved these changes

2020-01-06 16:52 UTC, sblondeau requested changes

2020-01-06 16:52 UTC, sblondeau commented on src/Repository/WorkerRepository.php
> +            ->orderBy('a.name', 'ASC')
il faut un second order by par nom de worker pour qu'ils soient classés alphabétiqeuemtn au sein d'une meme activité !

2020-01-07 09:18 UTC, ankwachu commented
j'ai fait un seul findBy avec une double requête c'est mieux?

2020-01-07 09:22 UTC, ankwachu commented on src/Repository/WorkerRepository.php
> +            ->orderBy('a.name', 'ASC')
j'ai fait un seul findBy avec une double requête c'est mieux?

2020-01-07 09:40 UTC, ghost approved these changes

2020-01-07 12:54 UTC, sblondeau approved these changes

2020-01-07 12:55 UTC, merged