initiate layout
WildCodeSchool/orleans-0919-php-gabare pull request #24
Opened 2019-12-02 16:09 UTC by ankwachu

2019-12-02 16:48 UTC, MathiasBln approved these changes

2019-12-02 21:22 UTC, sblondeau requested changes

2019-12-02 21:22 UTC, sblondeau commented on templates/layout.html.twig
> +<!DOCTYPE html>
non les fichiers layout et layout_admin doivent etendre de base.html.twig (justement pour ne pas à avoir à répéter les partie `<html><head>` etc.
De plus, si vous souhaitez ajouter font-awesome, il faut le faire via yarn (comme pour bootstrap) ça serait plus cohérent

2019-12-02 22:26 UTC, ankwachu commented on templates/layout.html.twig
> +<!DOCTYPE html>
done

2019-12-03 08:52 UTC, MathiasBln approved these changes

2019-12-03 09:51 UTC, sblondeau requested changes

2019-12-03 09:51 UTC, sblondeau commented on templates/base.html.twig
>              {{ encore_entry_link_tags('app') }}
non ! déjà on appelle pas de fichier scss dans un link car le navigateur ne sais pas les lire, ensuite le encore_entry_link_tags(app') a pour but de charger l'app.css !

2019-12-03 09:51 UTC, sblondeau commented on templates/base.html.twig
>      </head>
il me manque les blocs header et footer éventuellement

2019-12-03 12:49 UTC, bcarme approved these changes

2019-12-03 15:25 UTC, bcarme approved these changes

2019-12-03 15:37 UTC, sblondeau approved these changes

2019-12-03 15:37 UTC, merged