S04US14 - ajout partenaires
WildCodeSchool/orleans-0919-php-gabare pull request #242
Opened 2020-01-04 13:11 UTC by ankwachu

2020-01-05 18:07 UTC, ghost approved these changes

2020-01-06 11:17 UTC, sblondeau requested changes

2020-01-06 11:17 UTC, sblondeau commented on templates/about_us/includes/_partners.html.twig
> +            <div class="logo-partner text-center col-lg-3 col-md-4 col-xs-6">
tu pourrais peut etre me faire une petite boucle pour etre un peu plus DRY ;-)

2020-01-09 12:51 UTC, ghost approved these changes

2020-01-09 16:09 UTC, MathiasBln approved these changes

2020-01-09 21:27 UTC, sblondeau approved these changes

2020-01-09 21:27 UTC, merged