Fix rendez-vous client
WildCodeSchool/orleans-0919-php-gabare pull request #244
Opened 2020-01-06 09:56 UTC by ankwachu

2020-01-06 21:02 UTC, sblondeau requested changes

2020-01-06 21:02 UTC, sblondeau commented on templates/admin_article/show.html.twig
> +                <td><img src="{{ article.image }}" alt="" style="width: 400px;"></td>
style inline

2020-01-06 21:02 UTC, sblondeau commented on templates/join_us/includes/_forms.html.twig
> +<section class="welcome pt-5 pb-5" xmlns="http://www.w3.org/1999/html">
pourquoi ce xmlns ?

2020-01-07 07:58 UTC, ankwachu commented on templates/join_us/includes/_forms.html.twig
> +<section class="welcome pt-5 pb-5" xmlns="http://www.w3.org/1999/html">
bonne question

2020-01-07 08:43 UTC, bcarme approved these changes

2020-01-07 12:55 UTC, sblondeau approved these changes

2020-01-07 12:55 UTC, merged