S04 US46 - Add (Crud agenda)
WildCodeSchool/orleans-0919-php-gabare pull request #253
Opened 2020-01-06 16:39 UTC by bcarme

2020-01-06 16:46 UTC, ghost approved these changes

2020-01-06 21:04 UTC, sblondeau requested changes

2020-01-06 21:04 UTC, sblondeau commented on templates/admin_timetable/index.html.twig
> +    {% for label, messages in app.flashes(['success', 'danger']) %}
non ! on met l'affichage des messages flash une seule fois dans le base.html.twig et nul part ailleurs

2020-01-07 08:28 UTC, bcarme commented on templates/admin_timetable/index.html.twig
> +    {% for label, messages in app.flashes(['success', 'danger']) %}
je l'enlève, Lionel s'en occupe dans sa user story

2020-01-07 08:47 UTC, ankwachu approved these changes

2020-01-07 12:58 UTC, sblondeau approved these changes

2020-01-07 12:58 UTC, merged