S04 us91A - connexion API
WildCodeSchool/orleans-0919-php-gabare pull request #254
Opened 2020-01-07 12:17 UTC by ankwachu

2020-01-07 12:23 UTC, ghost approved these changes

2020-01-07 12:58 UTC, sblondeau requested changes

2020-01-07 12:58 UTC, sblondeau commented on src/Controller/ApiController.php
> +class ApiController extends AbstractController
Cette page sert à afficher les products, donc devrait s'appeler ProductController tout simplement

2020-01-07 12:58 UTC, sblondeau commented on src/Service/ConnectOdooService.php
> +        $database = 'test-lagabare';
ce sont des identifiants de connexion ! il ne faut surtout pas les écrires en clair. Il faut les passer dans le .env.local (pensé à mettre un "modèle" dans le .env) comme pour des identifiants de database ou de mail

2020-01-08 17:05 UTC, bcarme approved these changes

2020-01-08 21:04 UTC, sblondeau requested changes

2020-01-08 21:04 UTC, sblondeau commented on src/Controller/ProductController.php
> +    public function index(ConnectOdooService $connectOdooService, ProductRepository $productRepository): Response
le ConnecOdooService est inutile là

2020-01-08 23:03 UTC, ghost approved these changes

2020-01-09 11:29 UTC, sblondeau approved these changes

2020-01-09 11:29 UTC, merged