S01 us18
WildCodeSchool/orleans-0919-php-gabare pull request #26
Opened 2019-12-04 10:16 UTC by bcarme

2019-12-04 10:40 UTC, ghost approved these changes

2019-12-04 10:59 UTC, sblondeau requested changes

2019-12-04 10:59 UTC, sblondeau commented on templates/gabare_life/includes/_report.html.twig
> +                    <object data="" type="application/pdf" width="100%" height="100%">
inutile cette balise object, un simple lien doit être suffisant

2019-12-04 10:59 UTC, sblondeau commented on templates/gabare_life/includes/_report.html.twig
> +                    <object data="" type="application/pdf" width="100%" height="100%">
idem

2019-12-04 10:59 UTC, sblondeau commented on templates/gabare_life/includes/_report.html.twig
> +                    <p><b>Compte-rendu : Assemblée Générale Extraordinaire 10/10/2019</b></p>
la balise 'b' est à éviter, utilise plutot le CSS si tu veux mettre en gras

2019-12-04 11:53 UTC, MathiasBln approved these changes

2019-12-04 13:03 UTC, sblondeau approved these changes

2019-12-04 19:37 UTC, ankwachu approved these changes

2019-12-04 21:51 UTC, sblondeau requested changes

2019-12-04 21:51 UTC, sblondeau commented on src/Controller/GabareLifeController.php
>      public function index()
utilise plutot index(ReportRepository $reportRepository)
plutot que le getDoctrine->getRepo

2019-12-04 21:51 UTC, sblondeau commented on src/DataFixtures/AppFixtures.php
> +        // $product = new Product();
code commenté => le code reviewer ne devrait pas laisser passser !

2019-12-04 21:51 UTC, sblondeau commented on src/DataFixtures/AppFixtures.php
> +        $manager->flush();
mais d'ailleurs, j'ai l'impression que ce fichier ne sert à rien en fait ? donc à retirer

2019-12-04 21:51 UTC, sblondeau commented on src/Migrations/Version20191204150304.php
> +final class Version20191204150304 extends AbstractMigration
pas de migration ! il faut faire un doctrine:schema:update en dev
il faut déversionner ce fichier

2019-12-04 21:51 UTC, sblondeau commented on src/Repository/ReportRepository.php
> +    /*
pas de code commenté (meme si généré par Sf)

2019-12-04 21:51 UTC, sblondeau commented on templates/gabare_life/includes/_report.html.twig
> +                        <p class="font-weight-bold mb-0">Compte rendu : {{report.title}} - {{ report.meetingDate |date("m/d/Y") }}</p>
d/m/Y plutot en français ?

2019-12-05 10:43 UTC, LucasThvn commented on templates/gabare_life/index.html.twig
> +{% block title %}La vie de la Gabare{% endblock %}
L majuscule

2019-12-05 10:47 UTC, LucasThvn approved these changes

2019-12-05 10:59 UTC, ankwachu approved these changes

2019-12-05 11:43 UTC, bcarme commented on src/Controller/GabareLifeController.php
>      public function index()
Finalement c'est plus simple de laisser la méthode getDoctrine car on sinon on va tous passer un repo en paramètre index sur cette page là et ça sera moins lisible pour nous

2019-12-05 12:36 UTC, sblondeau approved these changes

2019-12-05 12:37 UTC, merged