creation of different user
WildCodeSchool/orleans-0919-php-gabare pull request #261
Opened 2020-01-08 08:27 UTC by MathiasBln

2020-01-08 08:59 UTC, ghost approved these changes

2020-01-08 11:27 UTC, sblondeau requested changes

2020-01-08 11:27 UTC, sblondeau commented on config/packages/security.yaml
> +        ROLE_SUPER_ADMIN: [ROLE_ADMIN_HOME, ROLE_ADMIN_WHO, ROLE_ADMIN_GABARE_LIFE, ROLE_ADMIN_JOIN_US]
c'est quoi tous ces roles ?

2020-01-08 11:27 UTC, sblondeau commented on src/Entity/User.php
> +     * @ORM\Column(type="string", length=180, unique=true)
Assert length et email

2020-01-08 13:06 UTC, MathiasBln commented on config/packages/security.yaml
> +        ROLE_SUPER_ADMIN: [ROLE_ADMIN_HOME, ROLE_ADMIN_WHO, ROLE_ADMIN_GABARE_LIFE, ROLE_ADMIN_JOIN_US]
Le client veux 1 admin par page, car ça fonctionne par secteur chez eux, ce n'est pas 1 personne qui gère tout mais 1 groupe qui gère une page

2020-01-09 16:19 UTC, ankwachu approved these changes

2020-01-09 21:28 UTC, sblondeau approved these changes

2020-01-09 21:28 UTC, merged