S01 us19
WildCodeSchool/orleans-0919-php-gabare pull request #28
Opened 2019-12-04 16:29 UTC by MathiasBln

Front of the presse zone

2019-12-04 19:38 UTC, ankwachu approved these changes

2019-12-04 22:06 UTC, sblondeau requested changes

2019-12-04 22:06 UTC, sblondeau commented on templates/gabare_life/includes/_presse.html.twig
> +                <img class="picture-article mb-4"
comme pour Barbara et Lionel, la page doit etre dynamique, donc il me faut une entité, un controlleur qui appelle un repository, etc. Pas une vue "en dur".
Du coup, des fixtures pour remplir un peu des données seraient égalemetn pertinentes !

2019-12-05 13:32 UTC, bcarme approved these changes

2019-12-05 21:53 UTC, sblondeau approved these changes

2019-12-06 08:04 UTC, bcarme approved these changes

2019-12-06 08:37 UTC, merged