S01 us01
WildCodeSchool/orleans-0919-php-gabare pull request #29
Opened 2019-12-04 17:10 UTC by LucasThvn

2019-12-04 19:41 UTC, ankwachu approved these changes

2019-12-04 22:10 UTC, sblondeau requested changes

2019-12-04 22:10 UTC, sblondeau commented on assets/scss/header_style
> +@import "vars";
manque l'extension .scss à ton fichier !

2019-12-04 22:10 UTC, sblondeau commented on templates/home/index.html.twig
> +{% block title %}Hello HomeController!{% endblock %}
Title à changer

2019-12-04 22:10 UTC, sblondeau commented on src/Controller/HomeController.php
> +     * @Route("/home", name="home")
la route "/" serait plus appropriée pour la page d'accueil

2019-12-05 10:37 UTC, ankwachu approved these changes

2019-12-05 22:03 UTC, sblondeau requested changes

2019-12-05 22:03 UTC, sblondeau commented on templates/_header.html.twig
> +        <a class="navbar-brand logo_nav p-0" href="#"><img src="../build/images/logo.png" alt="Logo de la gabare"></a>
il faut utiliser  {{assets('../build/images/logo.png')}}

2019-12-06 09:56 UTC, MathiasBln approved these changes

2019-12-06 10:00 UTC, sblondeau approved these changes

2019-12-06 10:00 UTC, merged