S05_US2_COOP
WildCodeSchool/orleans-0919-php-gabare pull request #296
Opened 2020-01-11 15:15 UTC by MathiasBln

add cooperateurs zone on the navbar

2020-01-12 10:16 UTC, ankwachu approved these changes

2020-01-13 08:23 UTC, sblondeau requested changes

2020-01-13 08:23 UTC, sblondeau commented on src/Controller/ArticleController.php
> +            'customers' => $customerRepository->countAll(),
ça fonctionne mais c'est très pénible d'avoir à refaire la requete sur chaque méthode. 
une meilleure solution est d'utiliser la fonction render() de Twig 
https://symfony.com/doc/current/templates.html#embedding-controllers
(une quete arrive là dessus, surement demain)

2020-01-13 20:25 UTC, sblondeau approved these changes

2020-01-13 20:25 UTC, merged