add admin animation show
WildCodeSchool/orleans-0919-php-gabare pull request #30
Opened 2019-12-05 12:02 UTC by ankwachu

2019-12-05 13:10 UTC, bcarme approved these changes

2019-12-06 08:42 UTC, sblondeau requested changes
tu as fusionner 2 US en une ici ! à redecouper

2019-12-06 08:42 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> + * @Route("/admin")
ça serait pas plutot /admin/animation ?

2019-12-06 08:42 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +     * @Route("/animation-ajouter", name="animation_new", methods={"GET","POST"})
et du coup là juste /ajouter ?

2019-12-06 08:42 UTC, sblondeau commented on src/Entity/Animation.php
> +     * @ORM\Column(type="string", length=255)
si tu gère le add, il faut que tu ajoute les @assert pour les verifs coté serveur

2019-12-06 08:42 UTC, sblondeau commented on templates/admin_animation/index.html.twig
> +        <h1>Liste des animations</h1>
cette page c'est sensé etre un autre US ! toi tu es sur l'add !

2019-12-06 08:42 UTC, sblondeau commented on templates/gabare_life/includes/_animation.html.twig
> +                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
pas de lorem ipsum, il faut que les données soient dynamiquement reprise de la BDD

2019-12-06 09:05 UTC, ankwachu commented on templates/admin_animation/index.html.twig
> +        <h1>Liste des animations</h1>
oui j'ai corrigé une faute d'orthographe

2019-12-07 11:44 UTC, closed without merging