S05_97A_ROLE
WildCodeSchool/orleans-0919-php-gabare pull request #330
Opened 2020-01-14 14:27 UTC by MathiasBln

change mail/password and roles path

2020-01-14 14:29 UTC, bcarme approved these changes

2020-01-14 16:14 UTC, ghost approved these changes

2020-01-14 21:33 UTC, sblondeau requested changes

2020-01-14 21:33 UTC, sblondeau commented on config/packages/security.yaml
> +         - { path: ^/admin/carousel, roles: ROLE_ADMIN_HOME }
je préfère que tu le configure au niveau de chaque méthode avec de @isGranted, je trouve ça plus clair et c'est dans les best practices de Sf.
tu peux config des routes "générales" ici, genre quand tout ce qui commence par /admin est réservé à ROLE_ADMIN, mais là ce n'est pas le cas.

2020-01-15 09:50 UTC, ankwachu approved these changes

2020-01-15 09:55 UTC, sblondeau approved these changes

2020-01-15 09:55 UTC, merged