fix card worker
WildCodeSchool/orleans-0919-php-gabare pull request #419
Opened 2020-01-23 15:52 UTC by ankwachu

2020-01-23 16:53 UTC, ghost requested changes

2020-01-23 16:53 UTC, Lionel21 commented on templates/about_us/includes/_CA-Friend.html.twig
> +                                <h4>{{ CAFriend.lastname }}</h4>
Il faut une cohérence au niveau des titres : tu mets un h4 alors qu'il n'y a pas de h3 au préalable dans ton code.

2020-01-24 09:28 UTC, ghost approved these changes

2020-01-25 17:21 UTC, ghost approved these changes

2020-01-26 20:15 UTC, sblondeau approved these changes

2020-01-26 20:15 UTC, merged