fix superAdmin
WildCodeSchool/orleans-0919-php-gabare pull request #458
Opened 2020-01-27 16:39 UTC by MathiasBln

super admin can't delete him and password nullable

2020-01-27 16:44 UTC, ghost approved these changes

2020-01-27 19:50 UTC, sblondeau requested changes

2020-01-27 19:50 UTC, sblondeau commented on templates/registration/edit.html.twig
> +            <div style="display: none">{{ form_row(form.roles) }}</div>
style inline => gateau

2020-01-28 08:23 UTC, sblondeau approved these changes

2020-01-28 08:24 UTC, sblondeau requested changes

2020-01-28 08:24 UTC, sblondeau commented on templates/registration/edit.html.twig
> +            {% if user.id == 1 %}
hum... tu veux faire quoi là ? 
si tu testes sur la valeur d'un id "en dur" dans ton code ça ne va pas

2020-01-28 10:00 UTC, MathiasBln commented on templates/registration/edit.html.twig
> +            {% if user.id == 1 %}
c'est pour que le choix des rôles soit caché pour le SuperAdmin quand il s'édite

2020-02-03 10:38 UTC, bcarme approved these changes

2020-02-03 10:59 UTC, ankwachu approved these changes

2020-02-03 12:00 UTC, sblondeau approved these changes

2020-02-03 12:00 UTC, sblondeau approved these changes

2020-02-03 12:00 UTC, merged