S01 us41
WildCodeSchool/orleans-0919-php-gabare pull request #65
Opened 2019-12-07 09:27 UTC by MathiasBln

style of the read page in admin_presse

2019-12-07 11:46 UTC, ankwachu approved these changes

2019-12-08 20:07 UTC, sblondeau requested changes
ça ne répond pas à ta US de lister les revues de presse en tant qu'admin, car la vue "list" n'est pas du tout sylisée.

2019-12-09 09:31 UTC, bcarme commented
Si si c'est stylisé sur l'index il y a des bouton de couleurs et un thead de couleur, ça reprend pour le moment ce qu'on a fait, on verra pour mettre un fond

2019-12-10 15:46 UTC, bcarme approved these changes

2019-12-10 15:52 UTC, sblondeau approved these changes

2019-12-10 15:52 UTC, merged