S02 us38
WildCodeSchool/orleans-0919-php-gabare pull request #69
Opened 2019-12-07 22:38 UTC by bcarme

2019-12-08 11:58 UTC, ankwachu approved these changes

2019-12-08 20:14 UTC, sblondeau requested changes

2019-12-08 20:14 UTC, sblondeau commented on src/Controller/GabareLifeController.php
> +                ->createQueryBuilder('r')
non un findBy suffit. Et si tu doit faire des requetes personnalisées ça serait dans la class ReportRepository direct

2019-12-08 20:14 UTC, sblondeau commented on src/Entity/Report.php
> +    * @Assert\NotBlank()
verif de la longueur

2019-12-08 20:14 UTC, sblondeau commented on src/Entity/Report.php
> +     * @Assert\NotBlank()
assert sur la length

2019-12-08 20:14 UTC, sblondeau commented on src/Form/ReportType.php
> +            ->add('link', TextType::class, [
si c'est une URL que tu attend ici, tu as un UrlType je crois

2019-12-08 20:14 UTC, sblondeau commented on templates/admin_report/edit.html.twig
> +    <a href="{{ path('report_index') }}">Retour à la liste</a>
tu n'as normalement pas à toucher au fichiers edit et delete dans une US qui touche uniquement au ADD ! 
laisse pour cette fois car il n'y a que très peu de texte impacté, mais fais attention pour les futures PR!

2019-12-09 09:53 UTC, ghost approved these changes

2019-12-09 11:10 UTC, sblondeau requested changes

2019-12-09 11:10 UTC, sblondeau commented on src/Entity/Report.php
> +     * @Assert\NotBlank()
vérif la longeur min est inutile, par contre un @Assert\Url doit etre ajouté

2019-12-09 11:10 UTC, sblondeau commented on src/Entity/Report.php
> +    * @Assert\NotBlank()
verifier la longueur min est inutile, tu sais déjà que c'est non null, après que ça fasse 1 ou 2 caractères n'est pas important

2019-12-09 13:06 UTC, ankwachu approved these changes

2019-12-09 16:30 UTC, sblondeau approved these changes

2019-12-09 16:30 UTC, merged