S02_US32 - delete function message animation
WildCodeSchool/orleans-0919-php-gabare pull request #82
Opened 2019-12-10 13:43 UTC by ankwachu

2019-12-10 16:13 UTC, sblondeau requested changes

2019-12-10 16:13 UTC, sblondeau commented on templates/admin_animation/_delete_form.html.twig
>      <button class="btn">Delete</button>
et là ? :p

2019-12-10 16:32 UTC, ankwachu commented on templates/admin_animation/_delete_form.html.twig
>      <button class="btn">Delete</button>
correction done

2019-12-11 09:35 UTC, MathiasBln approved these changes

2019-12-11 09:35 UTC, sblondeau approved these changes

2019-12-11 09:35 UTC, merged